version: '3.9'

services:
  app: 
    build:
      context: .
    command: >
      sh -c "python /manage.py wait_for_db &&
             python /manage.py migrate &&
             python /manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db  

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1306
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume reference
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root1306

volumes:
  pgdata:  # Ensure this is declared
